---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: "{}"
polling_verb:
framework_version: latest
serverless_language: node
polling_url:
polling_headers:
polling_body:
id: 407471
custom_fields:
- keyname: country
  name: Country
  field_type: select
  description: Show produce being harvested domestically this month.
  options:
  - United Kingdom
  - Ireland
  - United States
  - Canada
  - Australia
  - New Zealand
name: In Season
description: National fruit and veg harvests.
refresh_interval: 1440
