---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: "{}"
polling_verb:
framework_version: 3.2.0
serverless_language: node
polling_url:
polling_headers:
polling_body:
id: 407471
custom_fields:
- keyname: about_in_season
  name: About In Season
  field_type: author_bio
  description: See which fruit and vegetables are typically harvested this month in your country. Seasonal dates are national guides and may vary with local conditions.
  category: nature,life
  github_url: https://github.com/oneill9/trmnl-in-season
  learn_more_url: https://oneill9.github.io/trmnl-in-season/
- keyname: country
  name: Country
  field_type: select
  description: Show produce being harvested domestically this month.
  options:
  - United Kingdom
  - Ireland
  - United States
  - Canada
  - Australia
  - New Zealand
name: In Season
description: Monthly fruit and veg by country.
refresh_interval: 1440
